# Generated by Django 4.2 on 2023-07-28 08:10

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("degree", models.CharField(max_length=3)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
